import pytest

from codex_pro.cli.renderer_base import RenderSink, render_sink_implementation


class _Complete:
    def on_turn_accepted(self, event_id): ...
    def on_user_reply_token(self, inbound_id, text): ...
    def on_user_reply_reset(self, inbound_id): ...
    def on_user_reply_final(self, inbound_id, text): ...
    def on_tool_delivery(self, inbound_id, delivery_id, text): ...
    def on_cognitive(self, ev): ...
    def on_error(self, msg): ...
    def notify_disconnected(self): ...
    def notify_reconnected(self): ...
    def replay_missed_reply(self, text, event_id=""): ...


class _MissingOne:
    def on_turn_accepted(self, event_id): ...
    def on_user_reply_token(self, inbound_id, text): ...
    def on_user_reply_reset(self, inbound_id): ...
    def on_user_reply_final(self, inbound_id, text): ...
    def on_tool_delivery(self, inbound_id, delivery_id, text): ...
    def on_cognitive(self, ev): ...
    def on_error(self, msg): ...
    def notify_disconnected(self): ...
    def notify_reconnected(self): ...
    # replay_missed_reply missing


def test_complete_implementation_satisfies_protocol():
    assert isinstance(_Complete(), RenderSink)


def test_missing_method_fails_protocol():
    assert not isinstance(_MissingOne(), RenderSink)


def test_existing_tui_app_satisfies_protocol():
    # The Textual app is the reference implementation; if it drifts out of the
    # contract, the inline renderer and the bridge disagree about the sink.
    from codex_pro.cli.tui.app import CodexTUI
    for name in (
        "on_turn_accepted", "on_user_reply_token", "on_user_reply_reset",
        "on_user_reply_final", "on_tool_delivery", "on_cognitive", "on_error",
        "notify_disconnected", "notify_reconnected", "replay_missed_reply",
    ):
        assert callable(getattr(CodexTUI, name, None)), f"CodexTUI lacks {name}"


def test_executable_contract_rejects_signature_drift():
    class _WrongFinalSignature(_Complete):
        def on_user_reply_final(self, inbound_id): ...

    with pytest.raises(TypeError, match="on_user_reply_final expects 2"):
        render_sink_implementation(_WrongFinalSignature)


def test_executable_contract_rejects_async_bridge_callback():
    class _AsyncErrorCallback(_Complete):
        async def on_error(self, msg): ...

    with pytest.raises(TypeError, match="on_error must be synchronous"):
        render_sink_implementation(_AsyncErrorCallback)
