"""Setup wizard phases — re-exports from the main setup module.

This submodule provides the same public API as ``codex_pro.cli.setup``
for backward compatibility while allowing future independent evolution
of each phase.
"""
from __future__ import annotations

# Re-export everything from the main setup module
from codex_pro.cli.setup import (
    # Print helpers
    print_info,
    print_success,
    print_warning,
    print_error,
    # Channel definitions
    CHANNEL_DEFS,
    # Setup functions (phases)
    setup_language,
    setup_model,
    setup_permissions,
    setup_terminal,
    setup_agent,
    setup_tools,
    setup_channels,
    setup_gateway,
    setup_security,
    setup_observability,
    setup_evolution,
    setup_cost,
    setup_doctor,
    # Wizard orchestration
    run_setup_wizard,
    _run_setup_wizard,
    # Registry
    SETUP_SECTIONS,
    SECTION_ALIASES,
    section_names,
    # Doctor/reporting
    doctor_report,
    _capability_check,
    _doctor_mark,
    # Service helpers
    _wait_until_listening,
    _service_action,
    _report_started,
    _report_start_failed,
    _maybe_offer_web_build,
    _unstartable_reason,
    _browser_unreachable_reason,
    _browser_origin_compat_reason,
    _offer_gateway_start,
    _print_headless_guidance,
    # Initial setup
    _setup_config_target,
    _load_existing_config,
    _resolve_initial_locale,
    has_any_provider_configured,
    prompt_first_run_setup,
    # Internal helpers
    _resolve_workspace,
    _ensure_credential_key,
    _print_summary,
    _as_str,
    _probe_config,
    _installer_owns_service_registration,
    _print_linger_hint_if_needed,
    # Utility
    _print_banner,
    _print_section_header,
    _ensure_dict,
    _choice,
    t_provider_label,
    _detect_catalog_id,
    _handle_verify,
    _setup_weixin_qr,
    _bind_label,
    _primary_lan_address,
    _ask_allowed_hosts,
    _direct_http_origin,
    _ask_allowed_origins,
    _reconcile_loopback_allowed_hosts,
)

__all__ = [
    "print_info",
    "print_success",
    "print_warning",
    "print_error",
    "CHANNEL_DEFS",
    "setup_language",
    "setup_model",
    "setup_permissions",
    "setup_terminal",
    "setup_agent",
    "setup_tools",
    "setup_channels",
    "setup_gateway",
    "setup_security",
    "setup_observability",
    "setup_evolution",
    "setup_cost",
    "setup_doctor",
    "run_setup_wizard",
    "_run_setup_wizard",
    "SETUP_SECTIONS",
    "SECTION_ALIASES",
    "section_names",
    "doctor_report",
    "_capability_check",
    "_doctor_mark",
    "_wait_until_listening",
    "_service_action",
    "_report_started",
    "_report_start_failed",
    "_maybe_offer_web_build",
    "_unstartable_reason",
    "_browser_unreachable_reason",
    "_browser_origin_compat_reason",
    "_offer_gateway_start",
    "_print_headless_guidance",
    "_setup_config_target",
    "_load_existing_config",
    "_resolve_initial_locale",
    "has_any_provider_configured",
    "prompt_first_run_setup",
    "_resolve_workspace",
    "_ensure_credential_key",
    "_print_summary",
    "_as_str",
    "_probe_config",
    "_installer_owns_service_registration",
    "_print_linger_hint_if_needed",
    "_print_banner",
    "_print_section_header",
    "_ensure_dict",
    "_choice",
    "t_provider_label",
    "_detect_catalog_id",
    "_handle_verify",
    "_setup_weixin_qr",
    "_bind_label",
    "_primary_lan_address",
    "_ask_allowed_hosts",
    "_direct_http_origin",
    "_ask_allowed_origins",
    "_reconcile_loopback_allowed_hosts",
]
